import fs from "fs";
import os from "os";
import path from "path";
import { execSync } from "child_process";

type Shell = "zsh" | "bash" | "fish";

const SHELL_CONFIG_FILES: Record<Shell, string> = {
  zsh: "~/.zshrc",
  bash: "~/.bashrc",
  fish: "~/.config/fish/config.fish",
};

function detectShell(): Shell {
  const shellEnv = process.env["SHELL"] ?? "";
  if (shellEnv.includes("zsh")) return "zsh";
  if (shellEnv.includes("fish")) return "fish";
  return "bash";
}

/**
 * Generates a shell wrapper function for zsh / bash.
 *
 * Security model:
 *  - `gss switch` stdout is written to a tmpfile, never passed to eval directly
 *  - Each line is validated against a strict allowlist regex before eval
 *  - The regex permits ONLY: export GIT_INDEX_FILE="<path-safe-chars>"
 *  - Lines that don't match are silently discarded
 *  - All other `gss` subcommands bypass the wrapper entirely
 */
function posixWrapper(gssBin: string): string {
  return `\
# GSS — Git Shadow Session shell integration
# Generated by: gss config
# Remove this block to uninstall
gss() {
  if [ "\${1:-}" = "switch" ]; then
    local _tmpfile _rc _line
    _tmpfile="$(mktemp)"
    # stdout (env exports) → tmpfile ; stderr (status messages) → terminal
    "${gssBin}" "$@" > "$_tmpfile"
    _rc=$?
    if [ "$_rc" -eq 0 ]; then
      while IFS= read -r _line; do
        # Strict allowlist: only permit GIT_INDEX_FILE exports with safe path chars
        case "$_line" in
          export\\ GIT_INDEX_FILE=\\\"[A-Za-z0-9/._%-]*\\\")
            eval "$_line" ;;
        esac
      done < "$_tmpfile"
    fi
    rm -f "$_tmpfile"
    return "$_rc"
  fi
  "${gssBin}" "$@"
}`;
}

/**
 * Generates a fish shell wrapper function.
 */
function fishWrapper(gssBin: string): string {
  return `\
# GSS — Git Shadow Session shell integration
# Generated by: gss config --shell fish
# Remove this function to uninstall
function gss
    if test (count $argv) -gt 0; and test "$argv[1]" = "switch"
        set -l _tmpfile (mktemp)
        # stdout (env exports) → tmpfile ; stderr (status messages) → terminal
        "${gssBin}" $argv > $_tmpfile
        set -l _rc $status
        if test $_rc -eq 0
            while read -l _line
                # Strict allowlist: only permit GIT_INDEX_FILE exports
                if string match -qr '^export GIT_INDEX_FILE="[A-Za-z0-9/._%-]+"$' -- "$_line"
                    set -gx GIT_INDEX_FILE (string replace -r '^export GIT_INDEX_FILE="(.+)"$' '$1' -- "$_line")
                end
            end < $_tmpfile
        end
        rm -f $_tmpfile
        return $_rc
    end
    "${gssBin}" $argv
end`;
}

function resolveGssBin(): string {
  try {
    const bin = (execSync("command -v gss", { encoding: "utf8" }) as string).trim();
    if (bin) return bin;
  } catch {
    // fallback below
  }
  // Fallback: resolve relative to this module's location
  return path.resolve(process.argv[1] ?? "gss");
}

function expandHome(p: string): string {
  if (p.startsWith("~/")) return path.join(os.homedir(), p.slice(2));
  return p;
}

export function runConfig(opts: {
  shell?: string;
  install?: boolean;
}): void {
  const shell: Shell = (opts.shell as Shell | undefined) ?? detectShell();

  if (!["zsh", "bash", "fish"].includes(shell)) {
    console.error(
      `Unsupported shell: ${shell}\nSupported: zsh, bash, fish`
    );
    process.exit(1);
  }

  const gssBin = resolveGssBin();
  const code =
    shell === "fish" ? fishWrapper(gssBin) : posixWrapper(gssBin);

  if (!opts.install) {
    // Just print the snippet — user decides where to put it
    process.stdout.write(code + "\n");
    process.stderr.write("\n");
    process.stderr.write(`# Add the above to your shell config, or run:\n`);
    process.stderr.write(`#   gss config --shell ${shell} --install\n`);
    return;
  }

  // --install: append to the shell config file
  const configFile = expandHome(SHELL_CONFIG_FILES[shell]);

  // Idempotency check: don't append if already present
  if (fs.existsSync(configFile)) {
    const existing = fs.readFileSync(configFile, "utf8");
    if (existing.includes("GSS — Git Shadow Session shell integration")) {
      console.error(
        `GSS integration already present in ${configFile}\n` +
          `To update, remove the existing block and re-run.`
      );
      process.exit(1);
    }
  }

  fs.appendFileSync(configFile, "\n" + code + "\n");
  console.log(`GSS integration installed to ${configFile}`);
  console.log();
  console.log(
    shell === "fish"
      ? `Restart your shell or run:  source ${configFile}`
      : `Restart your shell or run:  source ${configFile}`
  );
  console.log();
  console.log("After that, use simply:");
  console.log("  gss switch <branch>");
}
